services:
  #  api:
  #    build:
  #      dockerfile: Dockerfile
  #      context: .
  #      target: production
  #    depends_on:
  #      - postgres
  #    volumes:
  #      - .:/usr/src/app
  #    command: npm run start:dev
  #    ports:
  #      - 3000:3000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8081:5432'
    volumes:
      - medium-clone-postgres:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 8082:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  medium-clone-postgres:

